// Parity of the non-compile CLI (convert, encode, decode, eval, and the compile
// error output) between the native capnp and every Wasm host: the upstream
// capnp-test.sh oracle, then conversion and eval matrices the upstream script
// does not cover, byte-compared with native. Hosts run concurrently because the
// wazero compiler engine recompiles the module in every process.

import { assert, assertBytesEqual } from "./lib/assert.ts";
import { copyTree } from "./lib/fs.ts";
import { guestCommand, wasmHosts } from "./lib/hosts.ts";
import { nativeBin, root, wasmBin } from "./lib/paths.ts";
import {
  decodeText,
  describeExit,
  expectSuccess,
  mustSucceed,
  run,
  type RunOptions,
} from "./lib/process.ts";
import { testSuite } from "./lib/workdir.ts";

const suite = testSuite("cli-parity-");

/** One way to run `capnp`: a command prefix that the tool's arguments follow. */
interface CliHost {
  name: string;
  command: readonly string[];
  /** Whether host paths below the staged tree must become guest paths. */
  guestPaths: boolean;
}

interface Staged {
  work: string;
  /** The staged upstream `src/` directory, mapped as guest `/` on Wasm hosts. */
  src: string;
  script: string;
  testdata: string;
  schema: string;
  hosts: CliHost[];
  /** Generated wrapper script per host, usable as capnp-test.sh's `CAPNP`. */
  wrappers: Map<string, string>;
}

let staged: Promise<Staged> | undefined;

function shellQuote(value: string): string {
  return `'${value.replaceAll("'", `'\\''`)}'`;
}

/**
 * A wrapper that capnp-test.sh can call as `$CAPNP`. The script derives every
 * path from its own location, so the arguments are host paths below `src`;
 * hosts that see `src` as guest `/` need those mapped, including the `-I` and
 * `--src-prefix` values the script passes.
 */
function wrapperScript(host: CliHost, src: string): string {
  const command = host.command.map(shellQuote).join(" ");
  if (!host.guestPaths) return `#!/usr/bin/env bash\nexec ${command} "$@"\n`;
  return `#!/usr/bin/env bash
# Generated by tests/cli_parity_test.ts: ${host.name} sees the staged tree as
# guest /, so host paths below it become guest paths.
root=${shellQuote(src)}
guest() {
  case $1 in
    "$root") printf / ;;
    "$root"/*) printf '%s' "\${1#"$root"}" ;;
    *) printf '%s' "$1" ;;
  esac
}
# capnp-test.sh derives --src-prefix from the first /src/ in its own path, which
# can lie above the staged root; an ancestor of the root can only be guest /.
prefix() {
  p=\${1%/}
  case $root/ in
    "$p"/*) printf / ;;
    *) guest "$1" ;;
  esac
}
args=()
for arg in "$@"; do
  case $arg in
    -I*) arg=-I$(guest "\${arg#-I}") ;;
    --src-prefix=*) arg=--src-prefix=$(prefix "\${arg#--src-prefix=}") ;;
    *) arg=$(guest "$arg") ;;
  esac
  args+=("$arg")
done
exec ${command} \${args[@]+"\${args[@]}"}
`;
}

/** Copies the upstream tree and prepares one wrapper per host, once. */
function stage(): Promise<Staged> {
  staged ??= (async () => {
    const work = await suite.workDir();
    // capnp-test.sh derives --src-prefix from the first `/src/` in its own
    // path, so the staged tree keeps upstream's `src/capnp` layout.
    const src = `${work}/src`;
    await copyTree(`${root}/ref/capnproto/c++/src/capnp`, `${src}/capnp`);
    // The launcher needs its package layout: the repository launcher, the
    // packaged runtime version, and the built compiler.
    const launcher = `${work}/launcher`;
    for (const directory of ["bin", "runtime", "wasm"]) {
      await Deno.mkdir(`${launcher}/${directory}`, { recursive: true });
    }
    await Deno.copyFile(`${root}/bin/capnp-wasm`, `${launcher}/bin/capnp-wasm`);
    await Deno.chmod(`${launcher}/bin/capnp-wasm`, 0o755);
    const pin = /^wasmtime = "([0-9]+\.[0-9]+\.[0-9]+)"$/m.exec(
      await Deno.readTextFile(`${root}/mise.toml`),
    )?.[1];
    assert(pin, "mise.toml has no exact Wasmtime pin");
    await Deno.writeTextFile(
      `${launcher}/runtime/wasmtime-version`,
      `${pin}\n`,
    );
    await Deno.copyFile(`${wasmBin}/capnp.wasm`, `${launcher}/wasm/capnp.wasm`);
    const hosts: CliHost[] = [
      { name: "native", command: [`${nativeBin}/capnp`], guestPaths: false },
      {
        name: "launcher",
        command: [
          `${launcher}/bin/capnp-wasm`,
          "compiler",
          "--workspace",
          src,
          "--",
        ],
        guestPaths: true,
      },
      ...wasmHosts.map((host) => ({
        name: host.name,
        command: guestCommand(host, "capnp", src),
        guestPaths: true,
      })),
    ];
    const wrappers = new Map<string, string>();
    await Deno.mkdir(`${work}/wrappers`);
    for (const host of hosts) {
      const path = `${work}/wrappers/${host.name}`;
      await Deno.writeTextFile(path, wrapperScript(host, src));
      await Deno.chmod(path, 0o755);
      wrappers.set(host.name, path);
    }
    return {
      work,
      src,
      script: `${src}/capnp/compiler/capnp-test.sh`,
      testdata: `${src}/capnp/testdata`,
      schema: `${src}/capnp/test.capnp`,
      hosts,
      wrappers,
    };
  })();
  return staged;
}

function seconds(started: number): string {
  return `${((performance.now() - started) / 1000).toFixed(1)}s`;
}

suite.test("upstream capnp-test.sh passes on every host", async () => {
  const { work, script, hosts, wrappers } = await stage();
  // A CAPNP that always fails must make the script fail: the oracle is live.
  const bogus = `${work}/wrappers/bogus`;
  await Deno.writeTextFile(bogus, "#!/bin/sh\nexit 1\n");
  await Deno.chmod(bogus, 0o755);
  const control = await run(["sh", script], {
    cwd: work,
    env: { CAPNP: bogus },
  });
  assert(
    !control.success && decodeText(control.stderr).includes("FAILED"),
    `capnp-test.sh ${describeExit(control)} with a failing CAPNP`,
  );
  // The script inherits stdin from /dev/null (run gives children no stdin), so
  // eval and the other commands without a redirection never wait on a pipe.
  const failures: string[] = [];
  await Promise.all(hosts.map(async (host) => {
    const started = performance.now();
    const result = await run(["sh", script], {
      cwd: work,
      env: { CAPNP: wrappers.get(host.name)! },
      timeoutMs: 600_000,
    });
    console.log(
      `capnp-test.sh on ${host.name}: ${seconds(started)}, ${
        describeExit(result)
      }`,
    );
    if (!result.success) {
      failures.push(
        `${host.name}: capnp-test.sh ${describeExit(result)}\n${
          decodeText(result.stderr)
        }`,
      );
    }
  }));
  assert(failures.length === 0, failures.join("\n\n"));
});

interface CliCase {
  label: string;
  args: string[];
  /** A file whose bytes are stdin; piped unless `regularFile` is set. */
  input?: string;
  /** Open the input as a regular file on stdin instead of piping it. */
  regularFile?: boolean;
}

suite.test(
  "conversions and eval match native byte for byte on every host",
  async () => {
    const { work, testdata, schema, hosts, wrappers } = await stage();
    const type = "TestAllTypes";
    const binary = await Deno.readFile(`${testdata}/binary`);
    // A stream of 200 messages exercises multi-message conversion.
    const stream = new Uint8Array(binary.length * 200);
    for (let index = 0; index < 200; index++) {
      stream.set(binary, index * binary.length);
    }
    await Deno.writeFile(`${work}/stream.bin`, stream);
    await Deno.writeFile(
      `${work}/canonical.bin`,
      await mustSucceed(
        [`${nativeBin}/capnp`, "convert", "binary:canonical", schema, type],
        { stdin: binary },
      ),
    );
    const convert = (
      formats: string,
      input: string,
      options: string[] = [],
      typed = true,
    ): CliCase => ({
      label: `convert ${formats} ${options.join(" ")} < ${
        input.slice(input.lastIndexOf("/") + 1)
      }`,
      args: [
        "convert",
        formats,
        ...options,
        ...(typed ? [schema, type] : []),
      ],
      input,
    });
    const cases: CliCase[] = [
      convert("binary:canonical", `${testdata}/binary`),
      convert("binary:canonical", `${testdata}/segmented`),
      convert("packed:canonical", `${testdata}/segmented-packed`),
      convert("flat:canonical", `${testdata}/flat`),
      convert("text:canonical", `${testdata}/pretty.txt`),
      convert("json:canonical", `${testdata}/pretty.json`),
      convert("canonical:text", `${work}/canonical.bin`),
      convert(
        "binary:binary",
        `${testdata}/binary`,
        ["--segment-size=4"],
        false,
      ),
      convert(
        "binary:packed",
        `${testdata}/binary`,
        ["--segment-size=4"],
        false,
      ),
      convert("binary:text", `${work}/stream.bin`),
      convert("binary:json", `${work}/stream.bin`, ["--short"]),
      convert("binary:packed", `${work}/stream.bin`, [], false),
      convert("binary:canonical", `${work}/stream.bin`, [], false),
      {
        ...convert("binary:canonical", `${testdata}/binary`),
        label: "convert binary:canonical < binary (regular-file stdin)",
        regularFile: true,
      },
    ];
    for (
      const constant of [
        "globalStruct",
        "globalPrintableStruct",
        "TestConstants.structConst",
      ]
    ) {
      for (
        const format of [
          "binary",
          "packed",
          "flat",
          "flat-packed",
          "canonical",
          "json",
          "text",
        ]
      ) {
        cases.push({
          label: `eval ${constant} -o${format}`,
          args: ["eval", schema, constant, `-o${format}`],
        });
      }
      cases.push({
        label: `eval ${constant} --short`,
        args: ["eval", schema, constant, "--short"],
      });
      cases.push({
        label: `eval ${constant} -ojson --short`,
        args: ["eval", schema, constant, "-ojson", "--short"],
      });
    }
    const inputs = new Map<string, Uint8Array>();
    for (const item of cases) {
      if (item.input && !inputs.has(item.input)) {
        inputs.set(item.input, await Deno.readFile(item.input));
      }
    }
    const stdinOf = (item: CliCase): RunOptions =>
      !item.input
        ? {}
        : item.regularFile
        ? { stdinFile: item.input }
        : { stdin: inputs.get(item.input)! };
    assert(
      new Set(cases.map((item) => item.label)).size === cases.length,
      "case labels are not unique",
    );
    const expected: Uint8Array[] = [];
    for (const item of cases) {
      expected.push(
        await mustSucceed([`${nativeBin}/capnp`, ...item.args], {
          ...stdinOf(item),
          label: `native ${item.label}`,
        }),
      );
    }
    const failures: string[] = [];
    await Promise.all(
      hosts.filter((host) => host.name !== "native").map(async (host) => {
        const started = performance.now();
        for (const [index, item] of cases.entries()) {
          const label = `${host.name}: ${item.label}`;
          try {
            const result = await run(
              [wrappers.get(host.name)!, ...item.args],
              stdinOf(item),
            );
            expectSuccess(result, label);
            assertBytesEqual(result.stdout, expected[index], label);
          } catch (error) {
            failures.push(error instanceof Error ? error.message : `${error}`);
          }
        }
        console.log(
          `${cases.length} conversions and evals on ${host.name}: ${
            seconds(started)
          }`,
        );
      }),
    );
    assert(failures.length === 0, failures.join("\n\n"));
  },
);

suite.test(
  "capnp-test.sh maps --src-prefix when the checkout path contains /src/",
  async () => {
    const { work } = await stage();
    // The script derives --src-prefix from the first /src/ in its own path. An
    // extra src component above the staged root reproduces a checkout under a
    // path such as ~/src/capnp-wasm, where that prefix is an ancestor of the
    // root rather than a path inside it.
    const nested = `${work}/nested/src/nest/src`;
    await copyTree(`${root}/ref/capnproto/c++/src/capnp`, `${nested}/capnp`);
    const wasmtime = wasmHosts.find((host) => host.name === "wasmtime");
    assert(wasmtime, "no wasmtime host");
    const host: CliHost = {
      name: "wasmtime-nested",
      command: guestCommand(wasmtime, "capnp", nested),
      guestPaths: true,
    };
    const wrapper = `${work}/wrappers/${host.name}`;
    await Deno.writeTextFile(wrapper, wrapperScript(host, nested));
    await Deno.chmod(wrapper, 0o755);
    const result = await run(["sh", `${nested}/capnp/compiler/capnp-test.sh`], {
      cwd: work,
      env: { CAPNP: wrapper },
      timeoutMs: 600_000,
    });
    expectSuccess(result, "capnp-test.sh with an ancestor --src-prefix");
  },
);
