import {
  type Compiler,
  createCompiler,
  type Language,
} from "../sdk/typescript/mod.ts";
import { assert, assertBytesEqual, assertTreesEqual } from "./lib/assert.ts";
import { readTree, writeTree } from "./lib/fs.ts";
import { guestCommand, wasmHosts } from "./lib/hosts.ts";
import { canonicalRequest, clangxx, nativeCompile } from "./lib/oracle.ts";
import { nativeBin, root, wasmBin, zigCacheDir } from "./lib/paths.ts";
import { buildTimeoutMs, mustSucceed } from "./lib/process.ts";
import { testSuite } from "./lib/workdir.ts";

const suite = testSuite("features-");
const fixtures = `${root}/tests/fixtures/features`;
const tools = {
  cpp: "capnpc-c++",
  rust: "capnpc-rust",
  go: "capnpc-go",
  zig: "capnpc-zig",
};
const manifest: {
  files: string[];
  scenarios: { name: string; entrypoints: string[]; generators: Language[] }[];
} = JSON.parse(await Deno.readTextFile(`${fixtures}/manifest.json`));

let compilerPromise: Promise<Compiler>;
function compiler() {
  return compilerPromise ??= (async () => {
    return await createCompiler({
      compiler: await Deno.readFile(`${wasmBin}/capnp.wasm`),
      generators: {
        cpp: await Deno.readFile(`${wasmBin}/capnpc-c++.wasm`),
        rust: await Deno.readFile(`${wasmBin}/capnpc-rust.wasm`),
        go: await Deno.readFile(`${wasmBin}/capnpc-go.wasm`),
        zig: await Deno.readFile(`${wasmBin}/capnpc-zig.wasm`),
      },
    });
  })();
}

for (const scenario of manifest.scenarios) {
  suite.test(`TypeScript SDK schema features: ${scenario.name}`, async (t) => {
    const work = await suite.workDir(`${scenario.name}-`);
    const files: Record<string, Uint8Array> = {};
    for (const name of manifest.files) {
      files[name] = await Deno.readFile(`${fixtures}/workspace/${name}`);
    }
    const includeFiles = {
      "capnp/c++.capnp": await Deno.readFile(
        `${root}/ref/capnproto/c++/src/capnp/c++.capnp`,
      ),
      "go.capnp": await Deno.readFile(`${root}/ref/go-capnp/std/go.capnp`),
    };
    await writeTree(`${work}/src`, files);
    await writeTree(`${work}/include`, includeFiles);
    const nativeRequest = await nativeCompile(
      scenario.entrypoints.map((name) => `${work}/src/${name}`),
      { include: [`${work}/include`], srcPrefix: `${work}/src`, cwd: work },
    );
    const result = await (await compiler()).compile({
      files,
      includeFiles,
      entrypoints: scenario.entrypoints,
      generators: scenario.generators,
    });
    assert(result.diagnostics.length === 0, "unexpected SDK diagnostics");
    await Deno.writeFile(`${work}/native-request.bin`, nativeRequest);
    await Deno.writeFile(`${work}/sdk-request.bin`, result.request);

    await t.step(
      "canonical full CodeGeneratorRequest equals native",
      async () => {
        assertBytesEqual(
          await canonicalRequest(result.request),
          await canonicalRequest(nativeRequest),
          `${scenario.name}: canonical request`,
        );
      },
    );

    for (const language of scenario.generators) {
      await t.step(`${language} generated bytes equal native`, async () => {
        const nativeOutput = `${work}/native-${language}`;
        await Deno.mkdir(nativeOutput);
        const stdout = await mustSucceed([`${nativeBin}/${tools[language]}`], {
          cwd: nativeOutput,
          stdin: nativeRequest,
          label: `native ${language} generator`,
        });
        assert(stdout.length === 0, `${language}: unexpected native stdout`);
        const expected = await readTree(nativeOutput);
        // Compare complete outputs against the maintained native command.
        // Zig's additive typed APIs intentionally differ from the pinned
        // pristine generator, even when binary reflection metadata is disabled.
        assert(
          expected.size ===
            scenario.entrypoints.length * (language === "cpp" ? 2 : 1),
          `${language}: unexpected native output count`,
        );
        await assertTreesEqual(
          result.outputs[language]!,
          expected,
          `${scenario.name}: ${language} output`,
        );
      });
    }

    await t.step(
      "schema inspection of the Wasm request equals native",
      async () => {
        // capnpc-capnp is shipped but has no SDK language; run the Wasm module
        // on the SDK's request and compare with native on the native request.
        const expected = await mustSucceed([`${nativeBin}/capnpc-capnp`], {
          stdin: nativeRequest,
          label: "native inspection",
        });
        const staging = `${work}/inspect`;
        await Deno.mkdir(staging);
        const actual = await mustSucceed(
          guestCommand(wasmHosts[0], "capnpc-capnp", staging),
          { stdin: result.request, label: "Wasm inspection" },
        );
        assert(expected.length > 0, "native inspection produced no output");
        assertBytesEqual(
          actual,
          expected,
          `${scenario.name}: schema inspection`,
        );
      },
    );

    await t.step("generated C++ defaults and pointers roundtrip", async () => {
      const output = `${work}/sdk-cpp`;
      await writeTree(output, result.outputs.cpp!);
      const executable = `${work}/consumer`;
      await mustSucceed(
        clangxx([
          "-std=c++23",
          `-I${root}/ref/capnproto/c++/src`,
          `-I${output}`,
          `${fixtures}/consumers/${scenario.name}.c++`,
          ...Object.keys(result.outputs.cpp!).filter((path) =>
            path.endsWith(".c++")
          ).map((path) => `${output}/${path}`),
          `${root}/build/native/lib/libcapnp.a`,
          `${root}/build/native/lib/libkj.a`,
          "-pthread",
          "-o",
          executable,
        ]),
        { cwd: work, label: "C++ consumer build", timeoutMs: buildTimeoutMs },
      );
      await mustSucceed([executable], { cwd: work, label: "C++ consumer" });
    });

    if (scenario.generators.includes("zig")) {
      await t.step(
        "generated Zig defaults and pointers roundtrip",
        async () => {
          const output = `${work}/sdk-zig`;
          await writeTree(output, result.outputs.zig!);
          // Keep nested generated imports inside the Zig module's root.
          await Deno.writeTextFile(
            `${output}/root.zig`,
            `pub const schema = @import("${
              scenario.entrypoints[0].replace(/\.capnp$/, ".zig")
            }");\n`,
          );
          await mustSucceed([
            "zig",
            "test",
            "--cache-dir",
            zigCacheDir,
            "--dep",
            "capnpc-zig",
            "--dep",
            "generated",
            `-Mroot=${root}/tests/consumers/zig/${scenario.name}.zig`,
            "--dep",
            "capnpc-zig",
            `-Mgenerated=${
              scenario.name === "values"
                ? `${output}/values.zig`
                : `${output}/root.zig`
            }`,
            `-Mcapnpc-zig=${root}/build/src/capnp-zig/src/lib_core.zig`,
          ], { label: "Zig consumer", timeoutMs: buildTimeoutMs });
        },
      );
    }
  });
}
