#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."
# shellcheck source=scripts/lib/export-source.sh
source scripts/lib/export-source.sh
# shellcheck source=scripts/lib/refs.sh
source scripts/lib/refs.sh
# shellcheck source=scripts/lib/lock.sh
source scripts/lib/lock.sh
acquire_build_lock build/locks/rust

require_pristine_ref capnproto-rust
revision="$(ref_revision capnproto-rust)"

# Cargo hashes a path dependency's absolute path into -C metadata, and so
# into symbol names and, under LTO, function order, unless the dependency
# lies inside the workspace root, where the path is hashed relative to that
# root. generators/rust depends on ref/capnproto-rust, which is outside its
# workspace, so the module bytes depended on the checkout path. The build
# therefore runs from a staged workspace under build/rust: an export of the
# recorded capnproto-rust revision and a copy of the generator crate at their
# repository-relative positions, under a generated workspace root that holds
# the release profile (Cargo ignores profiles of non-root packages). The
# export is excluded from that workspace so its crates keep inheriting from
# capnproto-rust's own workspace manifest.
workspace=build/rust
ensure_source_export ref/capnproto-rust "$revision" "$workspace/ref/capnproto-rust" \
  "$revision:pristine-v1" ""
rm -rf "$workspace/generators"
mkdir -p "$workspace/generators"
# -p keeps the sources' timestamps, so Cargo's fingerprints stay valid.
cp -Rp generators/rust "$workspace/generators/rust"
{
  printf '# Generated by scripts/build-rust.sh; edit generators/rust/Cargo.toml.\n'
  printf '[workspace]\nmembers = ["generators/rust"]\nexclude = ["ref"]\nresolver = "2"\n\n'
  sed -n '/^\[profile\./,$p' generators/rust/Cargo.toml
} > "$workspace/Cargo.toml"
sed -i.bak '/^\[profile\./,$d' "$workspace/generators/rust/Cargo.toml"
rm -f "$workspace/generators/rust/Cargo.toml.bak"
cp -p generators/rust/Cargo.lock "$workspace/Cargo.lock"
manifest="$workspace/Cargo.toml"

cargo build --locked --release --manifest-path "$manifest"

# Panic locations and other embedded paths name the checkout and the Cargo
# home; map both to fixed names so the module's bytes do not depend on where
# it was built (Cargo's trim-paths profile is unstable in the pinned
# toolchain). Only the WASI build gets them: CARGO_ENCODED_RUSTFLAGS would
# override the host-triple rustflags the toolchain environment may set for
# the native link. Rustflags from the environment stay in front.
root="$PWD"
wasm_rustflags=()
if [[ -n "${CARGO_ENCODED_RUSTFLAGS:-}" ]]; then
  IFS=$'\x1f' read -r -a wasm_rustflags <<< "$CARGO_ENCODED_RUSTFLAGS"
elif [[ -n "${RUSTFLAGS:-}" ]]; then
  read -r -a wasm_rustflags <<< "$RUSTFLAGS"
fi
wasm_rustflags+=(
  "--remap-path-prefix=$root=/capnpc-wasm"
  "--remap-path-prefix=${CARGO_HOME:-$HOME/.cargo}=/cargo-home"
)
encoded_rustflags="$(IFS=$'\x1f'; printf '%s' "${wasm_rustflags[*]}")"
CARGO_ENCODED_RUSTFLAGS="$encoded_rustflags" cargo build --locked --release \
  --manifest-path "$manifest" --target wasm32-wasip1

mkdir -p build/native/bin build/wasm/bin
cp "$CARGO_TARGET_DIR/release/capnpc-rust" build/native/bin/capnpc-rust
cp "$CARGO_TARGET_DIR/wasm32-wasip1/release/capnpc-rust.wasm" \
  build/wasm/bin/capnpc-rust.wasm
# The module contract (feature allow-list, no DWARF, no build-host paths,
# size budget) has one definition; check:wasm-artifacts applies it to dist/.
deno run --allow-read --allow-env=HOME --allow-run=wasm-tools \
  scripts/check-wasm-artifacts.ts --module build/wasm/bin/capnpc-rust.wasm
